In [ ]:
#important necessary modules
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import colormaps as cmap

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# Load in Data

Before loading in our data, we wanted to find the shared questions (features) across all years. Using the 2016 csv OSMI dataset, we assigned an integer to each question. For each question from 2016, we went through the 2017-2021 datasets to find questions that asked the same things (even if the wording was slightly different) and assigned shared questions across all years the same integer. If a question did not appear in all years from 2016-2021 surveys, that question did not get assigned an integer. A row containing these integers was added as the first row in each year's dataset.

In [ ]:
# load in raw data csv's updated with row containing number labels
df2016Updated = pd.read_csv('/content/drive/Shareddrives/DSCI400Data/2016updated.csv')
df2017Updated = pd.read_csv('/content/drive/Shareddrives/DSCI400Data/2017updated.csv')
df2018Updated = pd.read_csv('/content/drive/Shareddrives/DSCI400Data/2018updated.csv')
df2019Updated = pd.read_csv('/content/drive/Shareddrives/DSCI400Data/2019updated.csv')
df2020Updated = pd.read_csv('/content/drive/Shareddrives/DSCI400Data/2020updated.csv')
df2021Updated = pd.read_csv('/content/drive/Shareddrives/DSCI400Data/2021updated.csv')

# Filter Out Features

For each year's dataset, we filtered out features that contain null values in the first row (i.e., meaning the question did not appear in all years).

In [ ]:
def filterFeatures(df):
  """
    Input: pandas dataframe
    This function filters out features that contain null values in the first row (i.e., the number label row)
    Output: pandas dataframe with features filtered out
  """

  colsWithNull = df.columns[df.iloc[0].isnull()] #find features that contain a null value in the first row of input df
  df = df.drop(colsWithNull, axis=1) #drop those features
  return df

In [ ]:
#2016
df2016Filtered = filterFeatures(df2016Updated)
df2016Filtered

,Are you self-employed?,How many employees does your company or organization have?,Is your employer primarily a tech company/organization?,Is your primary role within your company related to tech/IT?,Does your employer provide mental health benefits as part of healthcare coverage?,Do you know the options for mental health care available under your employer-provided coverage?,"Has your employer ever formally discussed mental health (for example, as part of a wellness campaign or other official communication)?",Does your employer offer resources to learn more about mental health concerns and options for seeking help?,Is your anonymity protected if you choose to take advantage of mental health or substance abuse treatment resources provided by your employer?,"If a mental health issue prompted you to request a medical leave from work, asking for that leave would be:",...,Have you been diagnosed with a mental health condition by a medical professional?,Have you ever sought treatment for a mental health issue from a mental health professional?,"If you have a mental health issue, do you feel that it interferes with your work when being treated effectively?","If you have a mental health issue, do you feel that it interferes with your work when NOT being treated effectively?",What is your age?,What is your gender?,What country do you live in?,What US state or territory do you live in?,What country do you work in?,What US state or territory do you work in?
0,1,2,3.0,4.0,5,6,7,8,9,10,...,48,50,51,52,53,54,55,56,57,58
1,0,26-100,1.0,NaN,Not eligible for coverage / N/A,NaN,No,No,I don't know,Very easy,...,Yes,0,Not applicable to me,Not applicable to me,39,Male,United Kingdom,NaN,United Kingdom,NaN
2,0,25-Jun,1.0,NaN,No,Yes,Yes,Yes,Yes,Somewhat easy,...,Yes,1,Rarely,Sometimes,29,male,United States of America,Illinois,United States of America,Illinois
3,0,25-Jun,1.0,NaN,No,NaN,No,No,I don't know,Neither easy nor difficult,...,No,1,Not applicable to me,Not applicable to me,38,Male,United Kingdom,NaN,United Kingdom,NaN
4,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Yes,1,Sometimes,Sometimes,43,male,United Kingdom,NaN,United Kingdom,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1429,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,No,1,Not applicable to me,Not applicable to me,34,Female,United States of America,New York,United States of America,New York
1430,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Yes,0,Sometimes,Often,56,MALE,United States of America,California,Afghanistan,NaN
1431,0,100-500,1.0,NaN,Yes,Yes,Yes,Yes,I don't know,Somewhat difficult,...,Yes,1,Rarely,Sometimes,52,Male,United States of America,Georgia,United States of America,Georgia
1432,0,100-500,0.0,1.0,I don't know,I am not sure,No,Yes,I don't know,Somewhat difficult,...,Yes,0,Sometimes,Often,30,Female,United States of America,Nebraska,United States of America,Nebraska
1433,0,100-500,1.0,NaN,Yes,No,No,No,I don't know,Very difficult,...,No,0,Not applicable to me,Often,25,non-binary,Canada,NaN,Canada,NaN

In [ ]:
#2017
df2017Filtered = filterFeatures(df2017Updated)
df2017Filtered

,<strong>Are you self-employed?</strong>,How many employees does your company or organization have?,Is your employer primarily a tech company/organization?,Is your primary role within your company related to tech/IT?,Does your employer provide mental health benefits as part of healthcare coverage?,Do you know the options for mental health care available under your employer-provided health coverage?,"Has your employer ever formally discussed mental health (for example, as part of a wellness campaign or other official communication)?",Does your employer offer resources to learn more about mental health disorders and options for seeking help?,Is your anonymity protected if you choose to take advantage of mental health or substance abuse treatment resources provided by your employer?,"If a mental health issue prompted you to request a medical leave from work, how easy or difficult would it be to ask for that leave?",...,How willing would you be to share with friends and family that you have a mental illness?,Would you be willing to bring up a physical health issue with a potential employer in an interview?,Would you bring up your mental health with a potential employer in an interview?,<strong>Have you observed or experienced an unsupportive or badly handled response to a mental health issue in your current or previous workplace?</strong>,What is your age?,What is your gender?,What country do you <strong>live</strong> in?,What US state or territory do you <strong>live</strong> in?,What country do you <strong>work</strong> in?,What US state or territory do you <strong>work</strong> in?
0,1,2,3.0,4.0,5,6,7,8,9,10,...,40,61,62,41,53.0,54,55,56,57,58
1,0,100-500,1.0,1.0,No,Yes,No,I don't know,I don't know,I don't know,...,5,Yes,No,"Yes, I experienced",27.0,Female,United Kingdom,NaN,United Kingdom,NaN
2,0,100-500,1.0,1.0,Yes,Yes,No,No,I don't know,I don't know,...,4,Yes,No,"Yes, I observed",31.0,male,United Kingdom,NaN,United Kingdom,NaN
3,0,25-Jun,1.0,1.0,I don't know,No,I don't know,No,Yes,Difficult,...,5,Maybe,No,"Yes, I experienced",36.0,male,United States of America,Missouri,United States of America,Missouri
4,0,More than 1000,1.0,1.0,Yes,Yes,I don't know,I don't know,Yes,Difficult,...,10,No,No,Maybe/Not sure,22.0,Male,United States of America,Washington,United States of America,Washington
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
752,0,26-100,1.0,1.0,I don't know,No,No,I don't know,Yes,Very easy,...,8,Maybe,Maybe,Maybe/Not sure,41.0,Male,United Kingdom,NaN,United Kingdom,NaN
753,0,25-Jun,1.0,1.0,Yes,No,I don't know,No,Yes,Very easy,...,10,Yes,Maybe,Maybe/Not sure,40.0,Male,United States of America,Texas,United States of America,Texas
754,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1,Maybe,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN
755,0,26-100,1.0,1.0,Yes,Yes,No,No,No,Very easy,...,2,Maybe,No,No,30.0,dude,United States of America,Tennessee,United States of America,Tennessee
756,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#2018
df2018Filtered = filterFeatures(df2018Updated)
df2018Filtered

,<strong>Are you self-employed?</strong>,How many employees does your company or organization have?,Is your employer primarily a tech company/organization?,Is your primary role within your company related to tech/IT?,Does your employer provide mental health benefits as part of healthcare coverage?,Do you know the options for mental health care available under your employer-provided health coverage?,"Has your employer ever formally discussed mental health (for example, as part of a wellness campaign or other official communication)?",Does your employer offer resources to learn more about mental health disorders and options for seeking help?,Is your anonymity protected if you choose to take advantage of mental health or substance abuse treatment resources provided by your employer?,"If a mental health issue prompted you to request a medical leave from work, how easy or difficult would it be to ask for that leave?",...,How willing would you be to share with friends and family that you have a mental illness?,Would you be willing to bring up a physical health issue with a potential employer in an interview?,Would you bring up your mental health with a potential employer in an interview?,<strong>Have you observed or experienced an unsupportive or badly handled response to a mental health issue in your current or previous workplace?</strong>,What is your age?,What is your gender?,What country do you <strong>live</strong> in?,What US state or territory do you <strong>live</strong> in?,What country do you <strong>work</strong> in?,What US state or territory do you <strong>work</strong> in?
0,1,2,3.0,4.0,5,6,7,8,9,10,...,40,61,62,41,53,54,55,56,57,58
1,0,More than 1000,1.0,0.0,Yes,Yes,Yes,Yes,Yes,Somewhat difficult,...,3,No,No,"Yes, I observed",57,Female,Canada,NaN,Canada,NaN
2,0,More than 1000,1.0,1.0,Yes,Yes,No,I don't know,I don't know,Somewhat difficult,...,3,Yes,No,No,29,male,United States of America,Massachusetts,United States of America,Massachusetts
3,0,25-Jun,0.0,1.0,Yes,Yes,No,No,I don't know,Somewhat easy,...,2,No,No,No,46,Male,United States of America,Florida,United States of America,Florida
4,0,25-Jun,1.0,1.0,No,No,No,No,I don't know,Neither easy nor difficult,...,9,No,No,No,34,male,Norway,NaN,Norway,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
413,0,25-Jun,1.0,1.0,I don't know,No,No,No,I don't know,Very easy,...,5,Maybe,No,No,28,Male,United States of America,Tennessee,United States of America,Tennessee
414,0,100-500,0.0,1.0,Yes,Yes,No,Yes,Yes,Difficult,...,8,No,No,"Yes, I experienced",39,Male,Finland,NaN,Finland,NaN
415,0,100-500,0.0,1.0,Yes,Yes,I don't know,I don't know,I don't know,I don't know,...,8,Yes,No,No,31,Male,United States of America,New Jersey,United States of America,New Jersey
416,0,25-Jun,1.0,1.0,Yes,Yes,I don't know,Yes,I don't know,Somewhat easy,...,7,Yes,Yes,Maybe/Not sure,27,Male,United States of America,Tennessee,United States of America,Tennessee
417,0,More than 1000,0.0,1.0,Yes,Yes,No,No,Yes,I don't know,...,10,No,No,"Yes, I observed",35,Male,United States of America,Tennessee,United States of America,Tennessee

In [ ]:
#2019
df2019Filtered = filterFeatures(df2019Updated)
df2019Filtered

,*Are you self-employed?*,How many employees does your company or organization have?,Is your employer primarily a tech company/organization?,Is your primary role within your company related to tech/IT?,Does your employer provide mental health benefits as part of healthcare coverage?,Do you know the options for mental health care available under your employer-provided health coverage?,"Has your employer ever formally discussed mental health (for example, as part of a wellness campaign or other official communication)?",Does your employer offer resources to learn more about mental health disorders and options for seeking help?,Is your anonymity protected if you choose to take advantage of mental health or substance abuse treatment resources provided by your employer?,"If a mental health issue prompted you to request a medical leave from work, how easy or difficult would it be to ask for that leave?",...,How willing would you be to share with friends and family that you have a mental illness?,Would you be willing to bring up a physical health issue with a potential employer in an interview?,Would you bring up your *mental* health with a potential employer in an interview?,Have you observed or experienced an *unsupportive or badly handled response* to a mental health issue in your current or previous workplace?,What is your age?,What is your gender?,What country do you *live* in?,What US state or territory do you *live* in?,What country do you *work* in?,What US state or territory do you *work* in?
0,1,2,3,4,5,6,7,8,9,10,...,40,61,62,41,53,54,55,56,57,58
1,FALSE,26-100,TRUE,TRUE,I don't know,No,Yes,Yes,I don't know,Very easy,...,8,Yes,Maybe,No,25,Male,United States of America,Nebraska,United States of America,Nebraska
2,FALSE,26-100,TRUE,TRUE,Yes,No,No,Yes,Yes,I don't know,...,7,No,No,"Yes, I observed",51,male,United States of America,Nebraska,United States of America,Nebraska
3,FALSE,26-100,TRUE,TRUE,I don't know,No,No,I don't know,I don't know,Somewhat difficult,...,4,Maybe,No,Maybe/Not sure,27,Male,United States of America,Illinois,United States of America,Illinois
4,FALSE,100-500,TRUE,TRUE,I don't know,No,Yes,Yes,Yes,Very easy,...,3,No,No,No,37,male,United States of America,Nebraska,United States of America,Nebraska
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
348,FALSE,More than 1000,FALSE,TRUE,I don't know,No,No,I don't know,I don't know,Somewhat difficult,...,9,Maybe,No,"Yes, I observed",27,male,India,NaN,India,NaN
349,TRUE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3,Maybe,Maybe,"Yes, I observed",48,m,United States of America,Louisiana,United States of America,Louisiana
350,TRUE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10,Yes,No,I've always been self-employed,50,M,India,NaN,India,NaN
351,FALSE,More than 1000,TRUE,TRUE,No,No,No,No,Yes,Difficult,...,2,No,No,Maybe/Not sure,30,female,India,NaN,India,NaN
352,FALSE,More than 1000,TRUE,TRUE,Yes,Yes,No,Yes,Yes,Somewhat difficult,...,10,Maybe,Yes,Maybe/Not sure,24,Female (cis),United States of America,Oregon,United States of America,Oregon

In [ ]:
#2020
df2020Filtered = filterFeatures(df2020Updated)
df2020Filtered

,*Are you self-employed?*,How many employees does your company or organization have?,Is your employer primarily a tech company/organization?,Is your primary role within your company related to tech/IT?,Does your employer provide mental health benefits as part of healthcare coverage?,Do you know the options for mental health care available under your employer-provided health coverage?,"Has your employer ever formally discussed mental health (for example, as part of a wellness campaign or other official communication)?",Does your employer offer resources to learn more about mental health disorders and options for seeking help?,Is your anonymity protected if you choose to take advantage of mental health or substance abuse treatment resources provided by your employer?,"If a mental health issue prompted you to request a medical leave from work, how easy or difficult would it be to ask for that leave?",...,How willing would you be to share with friends and family that you have a mental illness?,Would you be willing to bring up a physical health issue with a potential employer in an interview?,Would you bring up your *mental* health with a potential employer in an interview?,Have you observed or experienced an *unsupportive or badly handled response* to a mental health issue in your current or previous workplace?,What is your age?,What is your gender?,What country do you *live* in?,What US state or territory do you *live* in?,What country do you *work* in?,What US state or territory do you *work* in?
0,1,2,3.0,4.0,5,6,7,8,9,10,...,40,61,62,41,53,54,55,56,57,58
1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5,Maybe,Maybe,Maybe/Not sure,45,Male,United States of America,Connecticut,United States of America,Connecticut
2,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10,Yes,Yes,"Yes, I observed",24,female,Russia,NaN,Russia,NaN
3,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5,Maybe,No,"Yes, I experienced",46,Male,India,NaN,India,NaN
4,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1,Yes,No,No,25,Female,Canada,NaN,Canada,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
176,0,More than 1000,0.0,1.0,No,No,No,No,No,Somewhat difficult,...,9,No,No,No,53,Male,United States of America,New York,United States of America,New York
177,0,26-100,1.0,1.0,Yes,Yes,Yes,Yes,I don't know,Very easy,...,4,Maybe,Maybe,"Yes, I experienced",23,F,Philippines,NaN,Philippines,NaN
178,0,100-500,1.0,1.0,I don't know,No,No,I don't know,I don't know,Somewhat easy,...,7,Maybe,No,No,34,Male,United States of America,Tennessee,United States of America,Tennessee
179,0,500-1000,0.0,1.0,Yes,No,Yes,Yes,Yes,Difficult,...,5,No,No,"Yes, I observed",43,Male,Canada,NaN,Canada,NaN
180,0,500-1000,1.0,1.0,Not eligible for coverage / NA,NaN,Yes,No,I don't know,Very easy,...,8,Yes,Yes,"Yes, I observed",37,male,Netherlands,NaN,Netherlands,NaN

In [ ]:
#2021
df2021Filtered = filterFeatures(df2021Updated)
df2021Filtered

,*Are you self-employed?*,How many employees does your company or organization have?,Is your employer primarily a tech company/organization?,Is your primary role within your company related to tech/IT?,Does your employer provide mental health benefits as part of healthcare coverage?,Do you know the options for mental health care available under your employer-provided health coverage?,"Has your employer ever formally discussed mental health (for example, as part of a wellness campaign or other official communication)?",Does your employer offer resources to learn more about mental health disorders and options for seeking help?,Is your anonymity protected if you choose to take advantage of mental health or substance abuse treatment resources provided by your employer?,"If a mental health issue prompted you to request a medical leave from work, how easy or difficult would it be to ask for that leave?",...,How willing would you be to share with friends and family that you have a mental illness?,Would you be willing to bring up a physical health issue with a potential employer in an interview?,Would you bring up your *mental* health with a potential employer in an interview?,Have you observed or experienced an *unsupportive or badly handled response* to a mental health issue in your current or previous workplace?,What is your age?,What is your gender?,What country do you *live* in?,What US state or territory do you *live* in?,What country do you *work* in?,What US state or territory do you *work* in?
0,1,2,3.0,4.0,5,6,7,8,9,10,...,40,61,62,41,53,54,55,56,57,58
1,0,26-100,1.0,1.0,I don't know,No,No,I don't know,I don't know,Very easy,...,2,Yes,No,No,28,Female,United States of America,Alaska,United States of America,Alaska
2,0,500-1000,1.0,1.0,Yes,No,Yes,Yes,Yes,I don't know,...,10,Maybe,No,"Yes, I observed",41,male,Brazil,NaN,Brazil,NaN
3,0,100-500,1.0,1.0,Yes,Yes,No,I don't know,I don't know,Somewhat easy,...,5,Maybe,Maybe,No,35,Male,Brazil,NaN,Brazil,NaN
4,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1,No,Maybe,Maybe/Not sure,20,male,Italy,NaN,Italy,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
127,0,26-100,1.0,1.0,No,No,No,No,I don't know,Somewhat easy,...,6,Maybe,No,"Yes, I experienced",33,Male,Germany,NaN,Germany,NaN
128,0,100-500,1.0,1.0,No,NaN,I don't know,No,I don't know,Somewhat easy,...,6,Maybe,No,No,49,Male,Portugal,NaN,Portugal,NaN
129,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,No,No,I've always been self-employed,28,NaN,Pakistan,NaN,Switzerland,NaN
130,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3,No,No,Maybe/Not sure,26,Male,India,NaN,India,NaN
131,0,26-100,1.0,1.0,I don't know,No,No,No,No,Somewhat difficult,...,6,Yes,No,"Yes, I observed",38,male,Slovenia,NaN,Slovenia,NaN

# Rename Columns and Combine Dataframes

We want to concatenate dataframes vertically so that columns representing the same question from different years are stacked on top of one another. To do this, we need the column names across the different years' dataframes to match, so we used the integer labels.

In [ ]:
def renameColHeaders(df):

  """
  Input: pandas dataframe with columns named as survey questions
  This function takes in a pandas dataframe and replaces the column headers containing survey questions with integers that we assigned to corresponding survey questions.
  Output: pandas dataframe with columns renamed to integer labels
  """

  df = df.rename(columns=df.iloc[0]).drop(df.index[0]) #renames columns to integers 
  df.columns = df.columns.astype(int) #makes all new column headers integer data values (some might've been string or floats)
  return df

In [ ]:
df2016Renamed = renameColHeaders(df2016Filtered)
df2016Renamed

,1,2,3,4,5,6,7,8,9,10,...,48,50,51,52,53,54,55,56,57,58
1,0,26-100,1.0,NaN,Not eligible for coverage / N/A,NaN,No,No,I don't know,Very easy,...,Yes,0,Not applicable to me,Not applicable to me,39,Male,United Kingdom,NaN,United Kingdom,NaN
2,0,25-Jun,1.0,NaN,No,Yes,Yes,Yes,Yes,Somewhat easy,...,Yes,1,Rarely,Sometimes,29,male,United States of America,Illinois,United States of America,Illinois
3,0,25-Jun,1.0,NaN,No,NaN,No,No,I don't know,Neither easy nor difficult,...,No,1,Not applicable to me,Not applicable to me,38,Male,United Kingdom,NaN,United Kingdom,NaN
4,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Yes,1,Sometimes,Sometimes,43,male,United Kingdom,NaN,United Kingdom,NaN
5,0,25-Jun,0.0,1.0,Yes,Yes,No,No,No,Neither easy nor difficult,...,Yes,1,Sometimes,Sometimes,43,Female,United States of America,Illinois,United States of America,Illinois
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1429,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,No,1,Not applicable to me,Not applicable to me,34,Female,United States of America,New York,United States of America,New York
1430,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Yes,0,Sometimes,Often,56,MALE,United States of America,California,Afghanistan,NaN
1431,0,100-500,1.0,NaN,Yes,Yes,Yes,Yes,I don't know,Somewhat difficult,...,Yes,1,Rarely,Sometimes,52,Male,United States of America,Georgia,United States of America,Georgia
1432,0,100-500,0.0,1.0,I don't know,I am not sure,No,Yes,I don't know,Somewhat difficult,...,Yes,0,Sometimes,Often,30,Female,United States of America,Nebraska,United States of America,Nebraska
1433,0,100-500,1.0,NaN,Yes,No,No,No,I don't know,Very difficult,...,No,0,Not applicable to me,Often,25,non-binary,Canada,NaN,Canada,NaN

In [ ]:
df2016Renamed.columns

Int64Index([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 13, 14, 17, 18, 19, 20, 21,
            22, 23, 24, 25, 26, 27, 28, 29, 30, 33, 34, 61, 62, 40, 41, 42, 43,
            44, 45, 48, 50, 51, 52, 53, 54, 55, 56, 57, 58],
           dtype='int64')

In [ ]:
df2017Renamed = renameColHeaders(df2017Filtered)
df2017Renamed

,1,2,3,4,5,6,7,8,9,10,...,40,61,62,41,53,54,55,56,57,58
1,0,100-500,1.0,1.0,No,Yes,No,I don't know,I don't know,I don't know,...,5,Yes,No,"Yes, I experienced",27.0,Female,United Kingdom,NaN,United Kingdom,NaN
2,0,100-500,1.0,1.0,Yes,Yes,No,No,I don't know,I don't know,...,4,Yes,No,"Yes, I observed",31.0,male,United Kingdom,NaN,United Kingdom,NaN
3,0,25-Jun,1.0,1.0,I don't know,No,I don't know,No,Yes,Difficult,...,5,Maybe,No,"Yes, I experienced",36.0,male,United States of America,Missouri,United States of America,Missouri
4,0,More than 1000,1.0,1.0,Yes,Yes,I don't know,I don't know,Yes,Difficult,...,10,No,No,Maybe/Not sure,22.0,Male,United States of America,Washington,United States of America,Washington
5,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10,Maybe,No,No,52.0,female,United States of America,Illinois,United States of America,Illinois
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
752,0,26-100,1.0,1.0,I don't know,No,No,I don't know,Yes,Very easy,...,8,Maybe,Maybe,Maybe/Not sure,41.0,Male,United Kingdom,NaN,United Kingdom,NaN
753,0,25-Jun,1.0,1.0,Yes,No,I don't know,No,Yes,Very easy,...,10,Yes,Maybe,Maybe/Not sure,40.0,Male,United States of America,Texas,United States of America,Texas
754,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1,Maybe,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN
755,0,26-100,1.0,1.0,Yes,Yes,No,No,No,Very easy,...,2,Maybe,No,No,30.0,dude,United States of America,Tennessee,United States of America,Tennessee
756,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df2017Renamed.columns

Int64Index([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 14, 13, 17, 18, 19, 20, 21,
            22, 23, 24, 25, 26, 27, 28, 29, 30, 34, 33, 45, 48, 44, 50, 43, 51,
            52, 42, 40, 61, 62, 41, 53, 54, 55, 56, 57, 58],
           dtype='int64')

In [ ]:
df2018Renamed = renameColHeaders(df2018Filtered)
df2018Renamed

,1,2,3,4,5,6,7,8,9,10,...,40,61,62,41,53,54,55,56,57,58
1,0,More than 1000,1.0,0.0,Yes,Yes,Yes,Yes,Yes,Somewhat difficult,...,3,No,No,"Yes, I observed",57,Female,Canada,NaN,Canada,NaN
2,0,More than 1000,1.0,1.0,Yes,Yes,No,I don't know,I don't know,Somewhat difficult,...,3,Yes,No,No,29,male,United States of America,Massachusetts,United States of America,Massachusetts
3,0,25-Jun,0.0,1.0,Yes,Yes,No,No,I don't know,Somewhat easy,...,2,No,No,No,46,Male,United States of America,Florida,United States of America,Florida
4,0,25-Jun,1.0,1.0,No,No,No,No,I don't know,Neither easy nor difficult,...,9,No,No,No,34,male,Norway,NaN,Norway,NaN
5,0,26-100,1.0,1.0,Yes,Yes,Yes,Yes,Yes,Somewhat easy,...,7,Yes,Yes,"Yes, I observed",29,Ostensibly Male,United States of America,Tennessee,United States of America,Tennessee
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
413,0,25-Jun,1.0,1.0,I don't know,No,No,No,I don't know,Very easy,...,5,Maybe,No,No,28,Male,United States of America,Tennessee,United States of America,Tennessee
414,0,100-500,0.0,1.0,Yes,Yes,No,Yes,Yes,Difficult,...,8,No,No,"Yes, I experienced",39,Male,Finland,NaN,Finland,NaN
415,0,100-500,0.0,1.0,Yes,Yes,I don't know,I don't know,I don't know,I don't know,...,8,Yes,No,No,31,Male,United States of America,New Jersey,United States of America,New Jersey
416,0,25-Jun,1.0,1.0,Yes,Yes,I don't know,Yes,I don't know,Somewhat easy,...,7,Yes,Yes,Maybe/Not sure,27,Male,United States of America,Tennessee,United States of America,Tennessee
417,0,More than 1000,0.0,1.0,Yes,Yes,No,No,Yes,I don't know,...,10,No,No,"Yes, I observed",35,Male,United States of America,Tennessee,United States of America,Tennessee

In [ ]:
df2018Renamed.columns

Int64Index([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 14, 13, 17, 18, 19, 20, 21,
            22, 23, 24, 25, 26, 27, 28, 29, 30, 34, 33, 45, 48, 44, 50, 43, 51,
            52, 42, 40, 61, 62, 41, 53, 54, 55, 56, 57, 58],
           dtype='int64')

In [ ]:
df2019Renamed = renameColHeaders(df2019Filtered)
df2019Renamed

,1,2,3,4,5,6,7,8,9,10,...,40,61,62,41,53,54,55,56,57,58
1,FALSE,26-100,TRUE,TRUE,I don't know,No,Yes,Yes,I don't know,Very easy,...,8,Yes,Maybe,No,25,Male,United States of America,Nebraska,United States of America,Nebraska
2,FALSE,26-100,TRUE,TRUE,Yes,No,No,Yes,Yes,I don't know,...,7,No,No,"Yes, I observed",51,male,United States of America,Nebraska,United States of America,Nebraska
3,FALSE,26-100,TRUE,TRUE,I don't know,No,No,I don't know,I don't know,Somewhat difficult,...,4,Maybe,No,Maybe/Not sure,27,Male,United States of America,Illinois,United States of America,Illinois
4,FALSE,100-500,TRUE,TRUE,I don't know,No,Yes,Yes,Yes,Very easy,...,3,No,No,No,37,male,United States of America,Nebraska,United States of America,Nebraska
5,FALSE,26-100,TRUE,TRUE,I don't know,No,I don't know,I don't know,I don't know,I don't know,...,1,No,No,No,46,m,United States of America,Nebraska,United States of America,Nebraska
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
348,FALSE,More than 1000,FALSE,TRUE,I don't know,No,No,I don't know,I don't know,Somewhat difficult,...,9,Maybe,No,"Yes, I observed",27,male,India,NaN,India,NaN
349,TRUE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3,Maybe,Maybe,"Yes, I observed",48,m,United States of America,Louisiana,United States of America,Louisiana
350,TRUE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10,Yes,No,I've always been self-employed,50,M,India,NaN,India,NaN
351,FALSE,More than 1000,TRUE,TRUE,No,No,No,No,Yes,Difficult,...,2,No,No,Maybe/Not sure,30,female,India,NaN,India,NaN
352,FALSE,More than 1000,TRUE,TRUE,Yes,Yes,No,Yes,Yes,Somewhat difficult,...,10,Maybe,Yes,Maybe/Not sure,24,Female (cis),United States of America,Oregon,United States of America,Oregon

In [ ]:
df2019Renamed.columns

Int64Index([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 14, 13, 17, 18, 19, 20, 21,
            22, 23, 24, 25, 26, 27, 28, 29, 30, 34, 33, 45, 48, 44, 50, 43, 51,
            52, 42, 40, 61, 62, 41, 53, 54, 55, 56, 57, 58],
           dtype='int64')

In [ ]:
df2020Renamed = renameColHeaders(df2020Filtered)
df2020Renamed

,1,2,3,4,5,6,7,8,9,10,...,40,61,62,41,53,54,55,56,57,58
1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5,Maybe,Maybe,Maybe/Not sure,45,Male,United States of America,Connecticut,United States of America,Connecticut
2,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10,Yes,Yes,"Yes, I observed",24,female,Russia,NaN,Russia,NaN
3,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5,Maybe,No,"Yes, I experienced",46,Male,India,NaN,India,NaN
4,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1,Yes,No,No,25,Female,Canada,NaN,Canada,NaN
5,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5,Yes,No,"Yes, I observed",25,F,Canada,NaN,Canada,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
176,0,More than 1000,0.0,1.0,No,No,No,No,No,Somewhat difficult,...,9,No,No,No,53,Male,United States of America,New York,United States of America,New York
177,0,26-100,1.0,1.0,Yes,Yes,Yes,Yes,I don't know,Very easy,...,4,Maybe,Maybe,"Yes, I experienced",23,F,Philippines,NaN,Philippines,NaN
178,0,100-500,1.0,1.0,I don't know,No,No,I don't know,I don't know,Somewhat easy,...,7,Maybe,No,No,34,Male,United States of America,Tennessee,United States of America,Tennessee
179,0,500-1000,0.0,1.0,Yes,No,Yes,Yes,Yes,Difficult,...,5,No,No,"Yes, I observed",43,Male,Canada,NaN,Canada,NaN
180,0,500-1000,1.0,1.0,Not eligible for coverage / NA,NaN,Yes,No,I don't know,Very easy,...,8,Yes,Yes,"Yes, I observed",37,male,Netherlands,NaN,Netherlands,NaN

In [ ]:
df2020Renamed.columns

Int64Index([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 14, 13, 17, 18, 19, 20, 21,
            22, 23, 24, 25, 26, 27, 28, 29, 30, 34, 33, 45, 48, 44, 50, 43, 51,
            52, 42, 40, 61, 62, 41, 53, 54, 55, 56, 57, 58],
           dtype='int64')

In [ ]:
df2021Renamed = renameColHeaders(df2021Filtered)
df2021Renamed

,1,2,3,4,5,6,7,8,9,10,...,40,61,62,41,53,54,55,56,57,58
1,0,26-100,1.0,1.0,I don't know,No,No,I don't know,I don't know,Very easy,...,2,Yes,No,No,28,Female,United States of America,Alaska,United States of America,Alaska
2,0,500-1000,1.0,1.0,Yes,No,Yes,Yes,Yes,I don't know,...,10,Maybe,No,"Yes, I observed",41,male,Brazil,NaN,Brazil,NaN
3,0,100-500,1.0,1.0,Yes,Yes,No,I don't know,I don't know,Somewhat easy,...,5,Maybe,Maybe,No,35,Male,Brazil,NaN,Brazil,NaN
4,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1,No,Maybe,Maybe/Not sure,20,male,Italy,NaN,Italy,NaN
5,0,More than 1000,0.0,1.0,Yes,No,Yes,Yes,I don't know,Difficult,...,8,No,No,No,35,female,Canada,NaN,Canada,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
127,0,26-100,1.0,1.0,No,No,No,No,I don't know,Somewhat easy,...,6,Maybe,No,"Yes, I experienced",33,Male,Germany,NaN,Germany,NaN
128,0,100-500,1.0,1.0,No,NaN,I don't know,No,I don't know,Somewhat easy,...,6,Maybe,No,No,49,Male,Portugal,NaN,Portugal,NaN
129,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,No,No,I've always been self-employed,28,NaN,Pakistan,NaN,Switzerland,NaN
130,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3,No,No,Maybe/Not sure,26,Male,India,NaN,India,NaN
131,0,26-100,1.0,1.0,I don't know,No,No,No,No,Somewhat difficult,...,6,Yes,No,"Yes, I observed",38,male,Slovenia,NaN,Slovenia,NaN

In [ ]:
df2021Renamed.columns

Int64Index([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 14, 13, 17, 18, 19, 20, 21,
            22, 23, 24, 25, 26, 27, 28, 29, 30, 34, 33, 45, 48, 44, 50, 43, 51,
            52, 42, 40, 61, 62, 41, 53, 54, 55, 56, 57, 58],
           dtype='int64')

In [ ]:
#with column names standardized across all the years, we can now concatenate the dataframes vertically
dfCombined = pd.concat([df2016Renamed, df2017Renamed, df2018Renamed, df2019Renamed, df2020Renamed, df2021Renamed], axis=0)
dfCombined

,1,2,3,4,5,6,7,8,9,10,...,51,52,53,54,55,56,57,58,61,62
1,0,26-100,1.0,NaN,Not eligible for coverage / N/A,NaN,No,No,I don't know,Very easy,...,Not applicable to me,Not applicable to me,39.0,Male,United Kingdom,NaN,United Kingdom,NaN,Maybe,Maybe
2,0,25-Jun,1.0,NaN,No,Yes,Yes,Yes,Yes,Somewhat easy,...,Rarely,Sometimes,29.0,male,United States of America,Illinois,United States of America,Illinois,Maybe,No
3,0,25-Jun,1.0,NaN,No,NaN,No,No,I don't know,Neither easy nor difficult,...,Not applicable to me,Not applicable to me,38.0,Male,United Kingdom,NaN,United Kingdom,NaN,Yes,Yes
4,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Sometimes,Sometimes,43.0,male,United Kingdom,NaN,United Kingdom,NaN,Yes,Maybe
5,0,25-Jun,0.0,1.0,Yes,Yes,No,No,No,Neither easy nor difficult,...,Sometimes,Sometimes,43.0,Female,United States of America,Illinois,United States of America,Illinois,Maybe,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
127,0,26-100,1.0,1.0,No,No,No,No,I don't know,Somewhat easy,...,Sometimes,Often,33.0,Male,Germany,NaN,Germany,NaN,Maybe,No
128,0,100-500,1.0,1.0,No,NaN,I don't know,No,I don't know,Somewhat easy,...,Not applicable to me,Not applicable to me,49.0,Male,Portugal,NaN,Portugal,NaN,Maybe,No
129,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Not applicable to me,Not applicable to me,28.0,NaN,Pakistan,NaN,Switzerland,NaN,No,No
130,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Sometimes,Sometimes,26.0,Male,India,NaN,India,NaN,No,No
131,0,26-100,1.0,1.0,I don't know,No,No,No,No,Somewhat difficult,...,Sometimes,Sometimes,38.0,male,Slovenia,NaN,Slovenia,NaN,Yes,No

# Filter Out Features with Too Many Null Values

Now that we have our combined dataframe, we want to make sure our features have enough data in them to be useful in our future models. We determined that if a feature has at least 70% non-null values, we will keep it.

In [ ]:
nullPerc = dfCombined.isnull().sum() / len(dfCombined) #calculate percentage of NA values in each feature
nonNullPerc = 1-nullPerc #subtract that percentage from 1 to calculate percentage of non-null values in each feature
colsToKeep = nonNullPerc[nonNullPerc > 0.7].index.tolist() #designate feature as one to keep if more than 70% of its values are non-null data that we can actually use
for col in colsToKeep:
    print(col)

1
2
3
5
6
7
8
9
10
13
14
25
26
27
28
29
30
33
34
40
41
43
44
45
50
51
52
53
54
55
57
61
62

In [ ]:
dfCombinedFinal = dfCombined[colsToKeep] #only keep features with at least 70% non-null values from combined dataframe
dfCombinedFinal.columns

Int64Index([ 1,  2,  3,  5,  6,  7,  8,  9, 10, 13, 14, 25, 26, 27, 28, 29, 30,
            33, 34, 40, 41, 43, 44, 45, 50, 51, 52, 53, 54, 55, 57, 61, 62],
           dtype='int64')

# Fixing the Gender Column

The question asking, "What is your gender?", is actually an open-ended question. However, because it asks about an essential piece of demographic information, we want to include it in our dataset for future modeling. Before we can vectorize this feature (column 54), we categorized each response as "male", "female", and "other".

In [ ]:
#make all responses in string format with lowercase letters
dfCombinedFinal[54] = dfCombinedFinal[54].str.lower()

#sort values in feature in descending order of highest to lowest count
gender_values = dfCombinedFinal[54].value_counts().sort_values(ascending=False).to_frame()
gender_values = gender_values.rename(columns={54: 'count'})
gender_values

<ipython-input-28-faa215d05c53>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfCombinedFinal[54] = dfCombinedFinal[54].str.lower()

                     count
male                  1896
female                 703
m                      281
f                      133
woman                   29
...                    ...
questioning              1
i have a penis           1
rr                       1
agender trans woman      1
non-binary/agender       1

[125 rows x 1 columns]

In [ ]:
#we went through all responses in the sort_values table to categorize them as either male or female
male = ["male", "m", "male-ish", "maile", "mal", "male (cis)", "make", "male ", "man","msle", "mail", "malr","cis man", "cis male"]
female = ["cis female", "f", "female", "woman",  "femake", "female ","cis-female/femme", "female (cis)", "femail"]
# other = ["trans-female", "something kinda male?", "queer/she/they", "non-binary","nah", "all", "enby", "fluid", 
#          "genderqueer", "androgyne", "agender", "male leaning androgynous", "guy (-ish) ^_^", "trans woman", "neuter", 
#          "female (trans)", "queer", "ostensibly male, unsure what that really means", "p", "a little about you"]

#changing responses to the gender question to either male or female depending on which gender category the response falls under
dfCombinedFinal[54].loc[dfCombinedFinal[54].isin(male)] = 'male'
dfCombinedFinal[54].loc[dfCombinedFinal[54].isin(female)] = 'female'

#any other response that doesn't fall under the "male" or "female" category is labeled as "other"
dfCombinedFinal[54] = dfCombinedFinal[54].apply(lambda x: 'other' if (x != "male" and x != "female") else x)
# data.Gender.loc[data.Gender.isin(other)] = 'others'

/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py:1732: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)
<ipython-input-29-480f7ed2449e>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfCombinedFinal[54] = dfCombinedFinal[54].apply(lambda x: 'other' if (x != "male" and x != "female") else x)

In [ ]:
dfCombinedFinal[54].unique()

array(['male', 'female', 'other'], dtype=object)

In [ ]:
#create csv of combined dataframe in shared google drive folder
from pathlib import Path  
filepath = Path('/content/drive/Shareddrives/DSCI400Data/dfcombinedfinal.csv')  
filepath.parent.mkdir(parents=True, exist_ok=True)  
dfCombinedFinal.to_csv(filepath)